the chromosome 6, partial trisomy 6q is a type of chromosomal disorder; chromosome 6, partial trisomy 6q produces growth retardation; chromosome 6, partial trisomy 6q produces mental retardation; chromosome 6, partial trisomy 6q produces malformations of the skull and facial (craniofacial) region; chromosome 6, partial trisomy 6q produces short, webbed neck; chromosome 6, partial trisomy 6q produces joint contractures; chromosome 6, partial trisomy 6q produces physical abnormalities; the chromosome 6, partial trisomy 6q is a type of chromosomal disorder.
the term "the disorder" refers back to the entity cryoglobulinemia; the acronym hcv stands for hepatitis c; the presence of the hepatitis c increases the risk of developing the mixed cryoglobulinemia; hepatitis c produces hepatitis.
the term "it" refers back to the entity tinnitus; rhythmic tinnitus produces tinnitus; the rhythmic tinnitus is a type of tinnitus; non-rhythmic tinnitus produces tinnitus; the non-rhythmic tinnitus is a type of tinnitus; rhythmic tinnitus produces tinnitus; rhythmic tinnitus produces tinnitus.
the term "the disorder" refers back to the entity lbsl.
arteriovenous malformation produces avm; arteriovenous malformation produces lesion; the acronym avm stands for arteriovenous malformation; avms produces lack of capillaries; avms produces blood traveling through the abnormal fistulous connections to flow rapidly; avm produces low resistance of the direct a-v connections; avm produces fistulas; avm produces high flow rates in the vessels; avm produces high flow rates; avm produces lower the pressure in the arteries; avm produces direct a-v connections; avm produces stroke.
the term "it" refers back to the entity scan1.
the pseudo-hurler polydystrophy is a type of genetic metabolic disorder; pseudo-hurler polydystrophy produces defective upd-n-acetylglucosamine-1-phosphotransferase; pseudo-hurler polydystrophy produces accumulation of mucopolysaccharides and mucolipids; the term "this disorder" refers back to the entity pseudo-hurler polydystrophy; the mucolipidosis type iii and the pseudo-hurler polydystrophy are synonyms; "this disorder" produces progressive joint stiffness; "this disorder" produces scoliosis; "this disorder" produces skeletal deformities of the hands; "this disorder" produces claw-hands; the mucolipidosis type ii and the i-cell disease are synonyms; pseudo-hurler polydystrophy produces growth delays; pseudo-hurler polydystrophy produces deterioration of the hip joints; pseudo-hurler polydystrophy produces clouding of the corneas of the eyes; pseudo-hurler polydystrophy produces mild to moderate coarseness of facial features; pseudo-hurler polydystrophy produces mild mental retardation; pseudo-hurler polydystrophy produces easy fatigability; pseudo-hurler polydystrophy produces heart disease; pseudo-hurler polydystrophy produces elevated lysosomal enzyme activity in serum; pseudo-hurler polydystrophy produces decreased enzyme levels in white blood cells; pseudo-hurler polydystrophy produces decreased enzyme levels in fibroblasts.
the term "the disorder" refers back to the entity gitelman syndrome; gitelman syndrome produces lower blood pressures.
the term "the disorder" refers back to the entity tarsal tunnel syndrome.
the dense deposit disease is a type of kidney disease; dense deposit disease produces abundance of a protein called c3 in the renal glomeruli; dense deposit disease produces dense 'sausage-like' deposits in the glomerular basement membrane; the acronym ddd stands for dense deposit disease; the acronym c3g stands for c3 glomerulopathy; ddd produces abundance of c3 in the renal glomeruli; the acronym c3gn stands for c3 glomerulonephritis; c3g produces kidney deposits.
ttd produces hair abnormalities; ttd produces short stature; ttd produces small chin; ttd produces ichthyosis; ttd produces intellectual impairment; ttd produces developmental delay; ttd produces bone and teeth anomalies; ttd produces developmental delay; ttd produces intellectual impairment; ttd produces abnormal patterns of myelination; ttd produces hair shafts tiger-tail pattern; ttd produces reduced sulfur content in patient's hair; ttd produces hair shaft abnormalities.
the alpers disease is a type of mental retardation; the presence of the alpers disease increases the risk of developing the serious liver disease; alpers disease produces increased muscle tone; alpers disease produces spasticity; alpers disease produces seizures; alpers disease produces dementia; alpers disease produces seizures; the term "it" refers back to the entity alpers disease; "it" produces lack of coordination of motor movement; "it" produces partial paralysis; "it" produces seizures; "it" produces muscle twitching; "it" produces hypotonia; alpers disease produces liver damage; alpers disease produces mental retardation; alpers disease produces loss of intellectual functions; alpers disease produces dementia; alpers disease produces spastic quadriplegia; alpers disease produces liver cirrhotic; alpers disease produces jaundice; alpers disease produces blind; alpers disease produces optic atrophy; the term "this disorder" refers back to the entity alpers disease.
the term "it" refers back to the entity hereditary ataxia; hereditary ataxia produces ataxia; hereditary ataxia produces ataxia; hereditary ataxia produces ataxias.
no relations present in the abstract.
ei produces red, blistering and denuded skin; ei produces skin thickening; ei produces blistering; ei produces scaling; ei produces skin thickening; ei produces scales; ei produces generalized erythroderma; the presence of the ei increases the risk of developing the skin infections; ei produces heat intolerance; ei produces palmoplantar keratoderma; palmoplantar keratoderma produces limit ambulation; palmoplantar keratoderma produces limit hand function; ichthyosis hystrix produces brown-grey hyperkeratotic spines; the ichthyosis hystrix is a type of ei; the curth-macklin and the ichthyosis hystrix are synonyms; ei produces blistering; ei produces palmoplantar keratoderma; the term "it" refers back to the entity ei.
banti syndrome produces obstruction of splenic veins; banti syndrome produces obstruction of hepatic or portal veins; banti syndrome produces hypertension splenic veins hepatic or portal veins; banti syndrome produces congenital blood clots; banti syndrome produces vascular obstruction; banti syndrome produces cirrhosis; the term "it" refers back to the entity banti syndrome; "it" produces increased arsenic levels.
the presence of the bilateral renal agenesis increases the risk of developing the potter syndrome; the term "this condition" refers back to the entity potter syndrome.
no relations present in the abstract.
the tuberculous meningitis is a type of meningitis; tuberculous meningitis produces inflammation of the meninges; the acronym tbm stands for tuberculous meningitis; the term "the disorder" refers back to the entity tbm; the term "the infection" refers back to the entity tbm; the term "it" refers back to the entity tuberculous meningitis; the term "this form of meningitis" refers back to the entity tuberculous meningitis; the acronym tb stands for tuberculosis; the presence of the miliary tuberculosis increases the risk of developing the tuberculous meningitis; the "this form of meningitis" is a type of meningitis; the term "it" refers back to the entity tbm; the term "the infection" refers back to the entity tbm.
the very long-chain acyl-coa dehydrogenase deficiency is a type of genetic disorder of fatty acid metabolism; the term "it" refers back to the entity very long-chain acyl-coa dehydrogenase deficiency; the acronym vlcadd stands for very long-chain acyl-coa dehydrogenase deficiency; "it" produces enzyme needed to break down certain very long-chain fatty acids is missing or not working properly; the vlcadd is a type of fatty acid oxidation (fod) diseases; the lcadd is a type of long-chain acyl-coa dehydrogenase deficiency; the acronym lcadd stands for long-chain acyl-coa dehydrogenase deficiency; the term "the disorder" refers back to the entity vlcad.
the enterobiasis is a type of common, contagious, parasitic infestation; the term "the disorder" refers back to the entity enterobiasis; the pinworm infection and the enterobiasis are synonyms; enterobiasis produces severe rectal itching.
the lichen sclerosus is a type of chronic inflammatory skin disorder; the term "it" refers back to the entity lichen sclerosus; the term "the disease" refers back to the entity balanitis xerotica obliterans; the term "the condition" refers back to the entity lichen sclerosus.
the term "the disorder" refers back to the entity crohn's disease; very early onset (veo) inflammatory bowel disease produces crohn's disease in children less than 6 years old; the term "it" refers back to the entity pediatric crohn's disease.
the alkaptonuria is a type of genetic metabolic disorder; alkaptonuria produces accumulation of homogentisic acid; alkaptonuria produces lack enough functional levels of an enzyme required to breakdown homogentisic acid; alkaptonuria produces dark urine; alkaptonuria produces urine that turns black when exposed to air; alkaptonuria produces dark urine; alkaptonuria produces asymptomatic during infancy or childhood; alkaptonuria produces ochronosis; alkaptonuria produces discoloration of the skin overlying cartilage; alkaptonuria produces sclera discolored; alkaptonuria produces progressive arthritis of the spine; alkaptonuria produces progressive arthritis of large joints; the term "it" refers back to the entity alkaptonuria; the term "the disorder" refers back to the entity alkaptonuria.
the primary lateral sclerosis is a type of neuromuscular disorder; primary lateral sclerosis produces progressive weakness of the muscles of the legs; primary lateral sclerosis produces stiffness of the muscles of the legs; primary lateral sclerosis produces weakness arms; primary lateral sclerosis produces weakness bulbar muscles; primary lateral sclerosis produces weakness muscles of the face; the term "the disorder" refers back to the entity primary lateral sclerosis; the acronym primary lateral sclerosis stands for primary lateral sclerosis; the primary lateral sclerosis is a type of stiffness of joints; motor neuron diseases produces malfunction of the motor neurons; the term "the disorder" refers back to the entity primary lateral sclerosis; primary lateral sclerosis produces spasticity; primary lateral sclerosis produces cramps; primary lateral sclerosis produces muscular contractions; primary lateral sclerosis produces stiffness of joints; primary lateral sclerosis produces ability to speak impaired; primary lateral sclerosis produces muscle weakness.
multifocal motor neuropathy produces slowly progressive muscle weakness; multifocal motor neuropathy produces slowly progressive muscle weakness of the arms; multifocal motor neuropathy produces slowly progressive muscle weakness of the g; the term "the disorder" refers back to the entity multifocal motor neuropathy; the term "this disorder" refers back to the entity multifocal motor neuropathy; the term "the disorder" refers back to the entity multifocal motor neuropathy; "the disorder" produces inflammation; "the disorder" produces abnormal functioning of the immune system; "the disorder" produces presence of specific autoantibodies that target a specific protein in the body; "the disorder" produces muscles cramps; "the disorder" produces atrophy of muscles; the term "the disorder" refers back to the entity multifocal motor neuropathy; the term "the disorder" refers back to the entity multifocal motor neuropathy; the term "the disorder" refers back to the entity multifocal motor neuropathy.
the alveolar soft part sarcoma is a type of slow growing soft tissue tumor; the term "it" refers back to the entity alveolar soft part sarcoma; the acronym asps stands for alveolar soft part sarcoma; the "it" is a type of sarcomas; the "it" is a type of soft tissue sarcomas; asps produces painless mass in the leg; asps produces painless mass in the buttock; the term "the sarcoma" refers back to the entity asps; the term "this disorder" refers back to the entity asps; the term "it" refers back to the entity asps; the "the sarcoma" is a type of sarcoma; "it" produces unbalanced translocation; the term "the disorder" refers back to the entity asps; the term "it" refers back to the entity asps; the term "this tumor" refers back to the entity asps; the asps is a type of soft tissue sarcomas; the soft tissue sarcomas is a type of cancers.
the hereditary nonspherocytic hemolytic anemia is a type of genetically transmitted blood disorders; hereditary nonspherocytic hemolytic anemia produces premature destruction of red blood cells; hereditary nonspherocytic hemolytic anemia produces anemia; the hereditary nonspherocytic hemolytic anemia is a type of blood disorder; the term "this disorder" refers back to the entity hereditary nonspherocytic hemolytic anemia.
the term "the disorder" refers back to the entity hartnup disease; the term "it" refers back to the entity hartnup disease.
the term "this" refers back to the entity soft tissue sarcomas; the soft tissue sarcomas is a type of tumors; the term "they" refers back to the entity soft tissue sarcomas; the soft tissue sarcomas is a type of cancers.
the cadasil is a type of genetic disorder; the term "the disorder" refers back to the entity cadasil; the term "the disease" refers back to the entity cadasil; the term "the disorder" refers back to the entity cadasil.
the berylliosis is a type of metal poisoning.
the cleidocranial dysplasia is a type of skeletal dysplasia; cleidocranial dysplasia produces short stature; cleidocranial dysplasia produces distinctive facial features; cleidocranial dysplasia produces narrow, sloping shoulders; cleidocranial dysplasia produces defective or absent collarbones; cleidocranial dysplasia produces premature closing of the coronal; cleidocranial dysplasia produces delayed closure of the fontanels; cleidocranial dysplasia produces narrow and abnormally shaped pelvic and pubic bones; cleidocranial dysplasia produces deformations in the chest; cleidocranial dysplasia produces delayed eruption of teeth; cleidocranial dysplasia produces short stature; cleidocranial dysplasia produces high arched palate; cleidocranial dysplasia produces wide pelvic joint; cleidocranial dysplasia produces failure of the lower jaw joints to unite; cleidocranial dysplasia produces fingers that are irregular in length; the term "this disorder" refers back to the entity cleidocranial dysplasia.
fetal alcohol syndrome produces mental and physical birth defects; fetal alcohol syndrome produces prenatal growth retardation; fetal alcohol syndrome produces postnatal growth retardation; fetal alcohol syndrome produces malformations of the skull and facial (craniofacial) region; fetal alcohol syndrome produces brain abnormalities; the acronym fas stands for fetal alcohol syndrome; fas produces varying degrees of mental retardation; fas produces learning abnormalities; fas produces behavioral problems; the acronym fas stands for fetal alcohol syndrome; fas produces mental retardation.
the trisomy 9p is a type of chromosomal syndrome; the down syndrome and the trisomy 21 are synonyms; the edwards's syndrome and the trisomy 18 are synonyms; the patau syndrome and the trisomy 13 are synonyms.
the glucose-galactose malabsorption is a type of inherited metabolic disorder; glucose-galactose malabsorption produces small intestine's inability to transport and absorb glucose and galactose; ggm produces watery diarrhea.
chromosome 9 ring produces malformations of the skull and facial (craniofacial) region; chromosome 9 ring produces growth retardation; chromosome 9 ring produces heart defects; chromosome 9 ring produces genital abnormalities; chromosome 9 ring produces moderate to severe intellectual disability; the chromosome 9 ring is a type of chromosomal abnormality; the term "the disorder" refers back to the entity chromosome 9 ring.
no relations present in the abstract.
congenital heart block produces heart block.
the primary central nervous system lymphoma is a type of brain tumors; the acronym pcnsl stands for primary central nervous system lymphoma; the presence of the hiv increases the risk of developing the primary cns lymphoma; the presence of the aids increases the risk of developing the primary cns lymphoma; the presence of the congenital immunodeficiency syndromes increases the risk of developing the primary cns lymphoma; the primary cns lymphoma is a type of brain tumor.
the hyperekplexia is a type of genetic disorder; the term "the disorder" refers back to the entity hyperekplexia.
dss produces muscle weakness; dss produces delayed motor milestones; the term "the condition" refers back to the entity dss; "the condition" produces hand and forearm muscles may become weak; dss produces respiratory insufficiency; dss produces mild vision difficulties; dss produces pain; dss produces loss of heat sensitivity; dss produces absence of reflexes; dss produces atrophy of leg muscles; dss produces scoliosis; dss produces ataxia; the acronym dss stands for dejerine-sottas syndrome; the term "this disorder" refers back to the entity dejerine-sottas syndrome; the term "it" refers back to the entity dejerine-sottas syndrome.
the dysplasia epiphysealis hemimelica is a type of bone disease; the term "it" refers back to the entity dysplasia epiphysealis hemimelica; the term "this condition" refers back to the entity dysplasia epiphysealis hemimelica; the term "it" refers back to the entity dysplasia epiphysealis hemimelica; the acronym deh stands for dysplasia epiphysealis hemimelica; the trevor's disease, and the dysplasia epiphysealis hemimelica are synonyms; "it" produces abnormal growth of cartilage arising from the cartilage of the terminal ends (epiphysis) of the long bones; "it" produces abnormal growth of cartilage arising from the cartilage of the terminal ends (epiphysis) of the long bones of the lower limbs; "it" produces abnormal cartilage; "it" produces irregular nodular mass located either in the medial or lateral part of the bone; the term "this condition" refers back to the entity deh; the term "this disease" refers back to the entity deh; the term "this disorder" refers back to the entity deh.
the dmd is a type of muscular dystrophy.
the term "they" refers back to the entity ameloblastic carcinoma.
the term "the disorder" refers back to the entity andersen-tawil syndrome.
fvs produces neural tube defects; fvs produces cleft lip and palate; fvs produces cardiovascular abnormalities; fvs produces genitourinary defects; fvs produces developmental delay; fvs produces endocrine disorders; fvs produces limb defects; fvs produces autism.
succinic semialdehyde dehydrogenase deficiency produces inborn error of metabolism; the term "the disorder" refers back to the entity succinic semialdehyde dehydrogenase deficiency; the acronym ssadh deficiency stands for succinic semialdehyde dehydrogenase deficiency; "the disorder" produces deficient activity of the ssadh enzyme; "the disorder" produces disrupts the metabolism of gamma-aminobutyric acid; ssadh deficiency produces abnormal accumulation of the compound succinic semialdehyde; ssadh deficiency produces succinic semialdehyde is reduced or converted to 4-hydroxybutyric acid also known as ghb; ssadh deficiency produces elevated levels of ghb in the urine; ssadh deficiency produces elevated levels of ghb in the plasma; ssadh deficiency produces elevated levels of ghb in the csf; ssadh deficiency produces 4-hydroxybutyric aciduria; ssadh deficiency produces gamma-hydroxybutyric aciduria.
ap-4-associated hsp produces spasticity; ap-4-associated hsp produces developmental delay; ap-4-associated hsp produces intellectual disability; ap-4-associated hsp produces seizures.
the chromosome 10, distal trisomy 10q is a type of chromosomal disorder; the term "the disorder" refers back to the entity chromosome 10, distal trisomy 10q; the term "the disorder" refers back to the entity chromosome 10, distal trisomy 10q.
cystic fibrosis produces pulmonary disease; cystic fibrosis produces pancreatic insufficiency; the term "the disease" refers back to the entity cystic fibrosis; the acronym cf stands for cystic fibrosis.
the laband syndrome is a type of genetic disorder; laband syndrome produces abnormalities of the head and facial (craniofacial) area; laband syndrome produces abnormalities of the hands; laband syndrome produces abnormalities of the feet; the term "this disorder" refers back to the entity laband syndrome; the zimmerman-laband syndrome and the laband syndrome are synonyms; "this disorder" produces gingival fibromatosis; "this disorder" produces overgrown gums; "this disorder" produces abnormally long, thin fingers; "this disorder" produces abnormally long, thin toes; "this disorder" produces dysplastic nails at birth; "this disorder" produces absent nails at birth; "this disorder" produces mental retardation; the term dysplastic nails at birth refers back to the entity overgrown gums; "the disorder" produces malformation or absence of the nails; laband syndrome produces gingival fibromatosis when the primary teeth appear.
the presence of the asd increases the risk of developing the dup15q.
the baller-gerold syndrome is a type of genetic disorder; the acronym bgs stands for baller-gerold syndrome; bgs produces distinctive misshaped appearance of the skull; bgs produces distinctive misshaped appearance of the facial (craniofacial) area; bgs produces distinctive misshaped appearance of the bones of the forearms and hands.
the batten turner type congenital myopathy is a type of myopathy; batten turner type congenital myopathy produces congenital hypotonia; the myopathy is a type of inherited muscle disease; the term "this disorder" refers back to the entity batten turner type congenital myopathy; batten turner type congenital myopathy produces in a newborn slow, progressive loss of muscle tone; batten turner type congenital myopathy produces in a newborn hypotonia; batten turner type congenital myopathy produces in a newborn general weakness; batten turner type congenital myopathy produces motor skills slightly delayed; batten turner type congenital myopathy produces important developmental milestones slightly delayed; the term "this disorder" refers back to the entity batten turner type congenital myopathy; "this disorder" produces toddlers mild muscle weakness; "this disorder" produces toddlers prone to falling; "this disorder" produces toddlers stumbling; the term "this disease" refers back to the entity batten turner type congenital myopathy; batten turner type congenital myopathy produces adults mild muscle weakness.
the term "the disorder" refers back to the entity protein s deficiency; the term "the disorder" refers back to the entity protein s deficiency.
the binder type nasomaxillary dysplasia is a type of congenital condition.
the lamellar ichthyosis is a type of genetic skin disorder; lamellar ichthyosis produces scale; the term "it" refers back to the entity lamellar ichthyosis.
the leukodystrophies is a type of progressive, metabolic, genetic diseases; leukodystrophy produces abnormal development or destruction of the white matter (myelin sheath) of the brain; leukodystrophies produces spasticity; leukodystrophies produces motor difficulties; leukodystrophies produces seizures; leukodystrophies produces burning paresthesia; leukodystrophies produces peripheral neuropathy; leukodystrophies produces neuropathic pain.
the creutzfeldt-jakob disease is a type of degenerative brain disorder; creutzfeldt-jakob disease produces rapidly progressive neuromuscular symptoms; creutzfeldt-jakob disease produces rapidly progressive neurological symptoms; creutzfeldt-jakob disease produces confusion; creutzfeldt-jakob disease produces depression; creutzfeldt-jakob disease produces behavioral changes; creutzfeldt-jakob disease produces impaired vision; creutzfeldt-jakob disease produces impaired coordination; the term "the disease" refers back to the entity creutzfeldt-jakob disease; the term "the disease" refers back to the entity creutzfeldt-jakob disease; the term "the disorder" refers back to the entity creutzfeldt-jakob disease; the acronym cjd stands for creutzfeldt-jakob disease; the spongiform encephalopathy and the creutzfeldt-jakob disease are synonyms; "the disease" produces dementia; "the disease" produces confusion; "the disease" produces disorientation; "the disease" produces impairment of memory control; "the disease" produces personality disintegration; "the disease" produces agitation; "the disease" produces restlessness; "the disease" produces neuromuscular abnormalities; "the disease" produces muscle weakness; "the disease" produces wasting; "the disease" produces myoclonus; "the disease" produces athetosis; "the disease" produces loss of physical and intellectual functions; "the disease" produces coma; "the disease" produces infections of the respiratory tract; the presence of the "the disease" increases the risk of developing the pneumonia.
the subacute sclerosing panencephalitis is a type of neurological disorder; subacute sclerosing panencephalitis produces encephalitis; the term "the disease" refers back to the entity subacute sclerosing panencephalitis; the acronym sspe stands for subacute sclerosing panencephalitis; the presence of the measles increases the risk of developing the "the disease"; the presence of the memory loss increases the risk of developing the neurological deterioration; sspe produces memory loss; sspe produces irritability; sspe produces seizures; sspe produces involuntary muscle movements; sspe produces behavioral changes; sspe produces neurological deterioration; the term "this disorder" refers back to the entity subacute sclerosing panencephalitis.
the waldenstrom's macroglobulinemia is a type of malignant disorder of the bone marrow and lymphatic tissues; the waldenstrom's macroglobulinemia is a type of lymphoma; waldenstrom's macroglobulinemia produces abnormally large numbers of a particular kind of white blood cell known as b lymphocytes; waldenstrom's macroglobulinemia produces excessive quantities of igm; the acronym wmg stands for waldenstrom's macroglobulinemia; "the disorder" produces large amounts of igm; "the disorder" produces blood to become thick; "the disorder" produces small blood vessels tear; "the disorder" produces bleeding in the nose; "the disorder" produces bleeding in the gums; "the disorder" produces bleeding in the retina; waldenstrom's macroglobulinemia produces fatigue; waldenstrom's macroglobulinemia produces loss of energy; waldenstrom's macroglobulinemia produces anemia; waldenstrom's macroglobulinemia produces bleeding from the nose; waldenstrom's macroglobulinemia produces bleeding from the gums; waldenstrom's macroglobulinemia produces enlarged liver; waldenstrom's macroglobulinemia produces enlarged spleen; waldenstrom's macroglobulinemia produces enlarged lymph nodes; peripheral neuropathy produces tingling in the fingers and toes; waldenstrom's macroglobulinemia produces blurring; waldenstrom's macroglobulinemia produces vision impairment; waldenstrom's macroglobulinemia produces changes in blood flow through the blood vessels that serve the retina; waldenstrom's macroglobulinemia produces viscous blood; the term "this disorder" refers back to the entity wmg; wmg produces bleeding of the retina; wmg produces low red blood cell; wmg produces low platelet counts.
the term "the disorder" refers back to the entity hyperferritinemia-cataract syndrome; the term "the disorder" refers back to the entity hyperferritinemia-cataract syndrome; the term "it" refers back to the entity hyperferritinemia-cataract syndrome; the term "the disorder" refers back to the entity hyperferritinemia-cataract syndrome; hyperferritinemia-cataract syndrome produces elevated levels of ferritin in the blood plasma.
west syndrome produces epileptic spasms; west syndrome produces infantile spasms; west syndrome produces abnormal brain wave patterns; west syndrome produces hypsarrhythmia; west syndrome produces intellectual disability; west syndrome produces spasms; west syndrome produces violent jackknife; west syndrome produces "salaam" movements; west syndrome produces mild twitching of the shoulder; west syndrome produces eye changes; west syndrome produces spasms; west syndrome produces epileptic spasms; west syndrome produces infantile spasms; west syndrome produces epileptic spasms; west syndrome produces epileptic spasms; west syndrome produces epileptic spasms.
the alagille syndrome is a type of genetic disorder; the term "the disorder" refers back to the entity alagille syndrome; "the disorder" produces cholestasis; "the disorder" produces jaundice; "the disorder" produces poor weight gain; "the disorder" produces poor growth; "the disorder" produces pruritis; "the disorder" produces pale, loose stools; "the disorder" produces heart murmurs; "the disorder" produces congenital heart defects; "the disorder" produces vertebral differences; "the disorder" produces thickening of posterior embryotoxon; "the disorder" produces distinctive facial features; the acronym algs stands for alagille syndrome.
elephantiasis produces gross enlargement of an area of the body, especially the limbs; elephantiasis produces obstruction of the lymphatic system; elephantiasis produces accumulation of a fluid called lymph in the affected areas.
the jejunal atresia is a type of genetic disorder; the term "this disorder" refers back to the entity jejunal atresia; the term "this disorder" refers back to the entity jejunal atresia; "this disorder" produces partial absence of the fold of the stomach membrane that connects the small intestine to the back wall of the abdomen; "this disorder" produces the jejunal twists around the marginal arter; "this disorder" produces atresia; "this disorder" produces vomiting; "this disorder" produces swollen abdomen; "this disorder" produces constipation; the term "it" refers back to the entity jejunal atresia.
the carnosinemia is a type of inherited metabolic disorder; carnosinemia produces developmental delays; carnosinemia produces seizures; carnosinemia produces drowsiness; carnosinemia produces myoclonic seizures; carnosinemia produces intellectual disability; carnosinemia produces drowsiness; carnosinemia produces seizures; the term "this disorder" refers back to the entity carnosinemia; developmental delays produces delayed intellectual development; developmental delays produces "this disorder"; developmental delays produces seizures; developmental delays produces myoclonic seizures.; developmental delays produces intellectual deficit; developmental delays produces intellectual disabilities; developmental delays produces developmental regression; developmental delays produces congenital myopathy; developmental delays produces congenital myopathy; developmental delays produces very low activity of the enzyme carnosinase in the blood; the term "this condition" refers back to the entity carnosinemia; carnosinemia produces abnormally high levels of carnosine and anserine in the serum and urine; carnosinemia produces very low activity of the enzyme carnosinase in the blood.
mikulicz syndrome produces enlargement of glands in the head and neck; mikulicz syndrome produces enlargement of glands in the parotids; mikulicz syndrome produces enlargement of glands lacrimal; mikulicz syndrome produces enlargement of glands salivary; the term "the disorder" refers back to the entity mikulicz syndrome; the term "it" refers back to the entity mikulicz syndrome; the acronym sle stands for lupus; the presence of the mikulicz syndrome increases the risk of developing the lymphomas; mikulicz syndrome produces xerostomia; mikulicz syndrome produces difficulty swallowing; mikulicz syndrome produces tooth decay; mikulicz syndrome produces enlarged lacrimal glands; mikulicz syndrome produces leading to absent or decreased tears; mikulicz syndrome produces enlarged parotid glands; mikulicz syndrome produces tumefactions of the salivary glands; mikulicz syndrome produces glands submaxillary swollen.
no relations present in the abstract.
no relations present in the abstract.
chromosome 14 ring produces psychomotor delays; chromosome 14 ring produces mental retardation; chromosome 14 ring produces growth delays; chromosome 14 ring produces seizures; the term "the disorder" refers back to the entity chromosome 14 ring; "the disorder" produces abnormalities of the head and facial (craniofacial) area; "the disorder" produces microcephaly; "the disorder" produces high forehead; "the disorder" produces elongated face; "the disorder" produces ocular hypertelorism; "the disorder" produces thin upper lip; "the disorder" produces flat nasal bridge; "the disorder" produces prominent nasal tip; "the disorder" produces large, low-set ears; the chromosomal disorders is a type of chromosomal disorder.
the ewing sarcoma is a type of bone tumor; the term "it" refers back to the entity ewing sarcoma; the extraosseous ewing sarcoma is a type of "it"; the term "these tumors" refers back to the entity ewing sarcoma; the term "these tumors" refers back to the entity ewing sarcoma; the term "these tumors" refers back to the entity primitive neuroectodermal tumor; the term "these tumors" refers back to the entity primitive neuroectodermal tumor; the acronym pnet stands for primitive neuroectodermal tumor; the "these tumors" is a type of ewing family of tumors; the term "this family" refers back to the entity ewing family of tumors; the term "these tumors" refers back to the entity ewing family of tumors; the acronym eft stands for ewing family of tumors; the extraosseous ewing sarcoma is a type of ewing sarcoma; the primitive neuroectodermal tumor is a type of ewing sarcoma; the askin's tumor is a type of ewing sarcoma; the ewing sarcoma is a type of "this family"; the term "it" refers back to the entity ewing sarcoma; the ewing sarcoma is a type of aggressive cancer.
the term "the disorder" refers back to the entity hypoplastic left heart syndrome; the hypoplastic left heart syndrome is a type of congenital heart defects; the term "this disorder" refers back to the entity hypoplastic left heart syndrome.
the term "the disorder" refers back to the entity fetal hydantoin syndrome.
infectious arthritis produces arthritis; infectious arthritis produces inflammation of one or more joints; infectious arthritis produces arthritis; the term "the infection" refers back to the entity infectious arthritis; "the infection" produces fever; "the infection" produces chills; "the infection" produces general weakness; "the infection" produces headaches; "the infection" produces inflammation and painful swelling of one or more joints of the body; infectious arthritis produces arthritis; hepatitis b produces hepatitis; infectious arthritis produces arthritis; arthritis produces rheumatoid arthritis; infectious arthritis produces arthritis; infectious arthritis produces arthritis; headaches produces arthritis; the term "the disorder" refers back to the entity headaches.
the townes-brocks syndrome is a type of autosomal dominant genetic disorder; townes-brocks syndrome produces imperforate anus; townes-brocks syndrome produces abnormal ears; townes-brocks syndrome produces hearing impairment; townes-brocks syndrome produces thumb malformations; townes-brocks syndrome produces abnormalities in the feet; townes-brocks syndrome produces abnormalities in the heart; townes-brocks syndrome produces abnormalities in the kidneys; the acronym tbs stands for townes-brocks syndrome; tbs produces imperforate anus; tbs produces small ears; tbs produces folded rim of skin and cartilage around the outer ear; tbs produces congenital sensorineural; tbs produces conductive hearing loss; tbs produces thumb malformations; tbs produces triphalangeal thumbs; tbs produces preaxial polydactyly; tbs produces feet anomalies; tbs produces short third toe; tbs produces overlapping toes; tbs produces flat feet; townes-brocks syndrome produces kidney dysfunction; townes-brocks syndrome produces kidney malformations; townes-brocks syndrome produces kidney anomalies; townes-brocks syndrome produces displaced or rotated kidneys; townes-brocks syndrome produces horseshoe kidney; townes-brocks syndrome produces polycystic kidneys; townes-brocks syndrome produces underdeveloped kidneys; townes-brocks syndrome produces abnormalities of the heart; townes-brocks syndrome produces abnormalities of the eye; townes-brocks syndrome produces abnormalities of the spine; townes-brocks syndrome produces mental retardation; the townes-brocks syndrome is a type of autosomal dominant genetic disorder; the term "this condition" refers back to the entity townes-brock syndrome.
the term "the disorder" refers back to the entity turner syndrome; the term "the disorder" refers back to the entity turner syndrome.
the cornelia de lange syndrome is a type of genetic disorder; cornelia de lange syndrome produces postnatal growth retardation; cornelia de lange syndrome produces abnormalities of the head and facial (craniofacial) area; cornelia de lange syndrome produces distinctive facial appearance; cornelia de lange syndrome produces malformations of the upper limbs; cornelia de lange syndrome produces intellectual disability; the term "the disorder" refers back to the entity cornelia de lange syndrome; the acronym cdls) stands for cornelia de lange syndrome; cdls) produces prenatal growth retardation; "the disorder" produces microbrachycephaly; "the disorder" produces prominent vertical philtrum; "the disorder" produces depressed nasal bridge; "the disorder" produces anteverted nares; "the disorder" produces maxillary prognathism; "the disorder" produces micrognathia; "the disorder" produces characteristic facial abnormalities; "the disorder" produces thin, downturned lips; "the disorder" produces low-set ears; "the disorder" produces synophrys; "the disorder" produces low hairline on the forehead and the back of the neck; "the disorder" produces curly, unusually long eyelashes; cdls produces malformations of the limbs; cdls produces small hands; cdls produces small feet; cdls produces clinodactyly; cdls produces syndactyly; cdls produces absence of the forearms, hands, and fingers; cdls produces feeding difficulties; cdls produces breathing difficulties; the presence of the cdls increases the risk of developing the respiratory infections; cdls produces low-pitched "growling" cry and low voice; cdls produces heart defects; cdls produces delayed skeletal maturation; cdls produces hearing loss; cdls produces physical abnormalities.
the cat eye syndrome is a type of chromosomal disorder; the acronym ces stands for cat eye syndrome; cat eye syndrome produces eye abnormality; cat eye syndrome produces coloboma; cat eye syndrome produces gap in the iris below the pupil; cat eye syndrome produces elongated pupil; cat eye syndrome produces appearance of a cat's eye; the term "the syndrome" refers back to the entity ces; the term "the disorder" refers back to the entity ces; the term "this syndrome" refers back to the entity ces.
the term "it" refers back to the entity buerger's disease; the thromboangiitis obliterans and the buerger's disease are synonyms; "it" produces narrowing or blockage (occlusion) of the veins and arteries of the extremities; "it" produces peripheral vascular disease; "it" produces extreme pain of the legs; "it" produces extreme pain of the lower arms while at rest; "it" produces cramping in the legs when they walk; "it" produces claudication; buerger's disease produces ulcers on the extremities; buerger's disease produces raynaud's phenomenon; buerger's disease produces thrombophlebitis; buerger's disease produces gangrene.
the human monocytic ehrlichiosis is a type of infectious disease; the human monocytic ehrlichiosis is a type of human ehrlichioses; the acronym hme stands for human monocytic ehrlichiosis; the term "these diseases" refers back to the entity human ehrlichioses; the term "the disorders" refers back to the entity human ehrlichioses; the human monocytic ehrlichiosis is a type of human ehrlichioses; the sennetsu fever is a type of human ehrlichioses; sennetsu fever produces fever; the human granulocytic ehrlichiosis is a type of human ehrlichioses.
the term "this disorder" refers back to the entity pycnodysostosis; the term "it" refers back to the entity pycnodysostosis.
empty sella syndrome produces enlargement or malformation of sella turcica; partially empty sella produces sella turcica is either partially filled with cerebrospinal fluid; partially empty sella produces very small associated pituitary gland lying in the floor of the sella; completely empty sella produces completely filled with cerebrospinal fluid with no visualized pituitary gland; empty sella syndrome produces hormone deficiencies; the presence of the empty sella syndrome increases the risk of developing the "it"; the presence of the pituitary tumor increases the risk of developing the "it"; the presence of the idiopathic intracranial hypertension increases the risk of developing the "it"; idiopathic intracranial hypertension produces elevated intracranial; the hormone deficiencies and the completely filled with cerebrospinal fluid with no visualized pituitary gland are synonyms; primary empty sella syndrome produces hypertension; the term "the disorder" refers back to the entity empty sella syndrome; the term "the disorder" refers back to the entity empty sella syndrome.
the term "this disorder" refers back to the entity acc; the acronym acc stands for acc; "it" produces partial or complete absence (agenesis) of an area of the brain that connects the two cerebral hemispheres; the term "it" refers back to the entity agenesis of corpus callosum; the term "it" refers back to the entity agenesis of corpus callosum; "it" produces developmental disturbance of the fetal brain; the presence of the fetal alcohol syndrome increases the risk of developing the acc; fetal alcohol syndrome produces mental retardation; the term "it" refers back to the entity agenesis of corpus callosum; the term "this condition" refers back to the entity agenesis of corpus callosum; spina bifida produces open (or non-fused) spine; spina bifida produces meningocele; spina bifida produces meningomyelocele; the term "this disorder" refers back to the entity spina bifida.
nephrotic syndrome produces renal insufficiency; nephrotic syndrome produces hypocalcemia; nephrotic syndrome produces muscle weakness; nephrotic syndrome produces kidney disease; nephrotic syndrome produces proteinuria; nephrotic syndrome produces deletion 22q11 syndrome; nephrotic syndrome produces hematuria; nephrotic syndrome produces nephrotic syndrome; progressive sensorineural deafness produces deafness; the term "the disease" refers back to the entity barakat syndrome; the term "this syndrome" refers back to the entity barakat syndrome; the term "the syndrome" refers back to the entity barakat syndrome.
the kienbock disease is a type of acquired bone disorder; kienbock disease produces abnormalities of the lunate bone in the wrist; kienbock disease produces recurrent pain; kienbock disease produces stiffness; kienbock disease produces thickening, swelling and tenderness in soft tissue overlying the lunate bone; kienbock disease produces degenerative changes in the lunate bone of the wrist; kienbock disease produces softening, deterioration, fragmentation or compression of the affected bone; kienbock disease produces pain; kienbock disease produces swelling; kienbock disease produces tenderness; kienbock disease produces thickening; kienbock disease produces stiffness; kienbock disease produces range of motion may become restricted; kienbock disease produces negative ulnar variance.
the term "the disorder" refers back to the entity alport syndrome; the presence of the chronic kidney disease increases the risk of developing the alport syndrome; the presence of the end-stage renal disease increases the risk of developing the alport syndrome.
the acanthosis nigricans is a type of skin condition; acanthosis nigricans produces hyperkeratosis of the skin; acanthosis nigricans produces hyperpigmentation of the skin; the acronym an stands for acanthosis nigricans; the term "the disorder" refers back to the entity an; the presence of the obesity increases the risk of developing the "the disorder".
the schindler disease is a type of inherited metabolic disorder; schindler disease produces deficient activity of the lysosomal enzyme alpha-n-acetylgalactosaminidase; schindler disease produces abnormal accumulation of glycosphingolipids, glycoproteins, and oligosaccharides; the term "type i" refers back to the entity schindler disease type i; the term "type ii" refers back to the entity schindler disease type ii; the term "the disorder" refers back to the entity schindler disease; the schindler disease is a type of lysosomal storage diseases; the term "these disorders" refers back to the entity lysosomal storage diseases; the gaucher diseases is a type of lysosomal storage diseases; the fabry diseases is a type of lysosomal storage diseases; the alpha-n-acetylgalactosaminidase deficiency is a type of "these disorders"; the alpha-n-acetylgalactosaminidase deficiency and the schindler disease are synonyms.
the term "the disorder" refers back to the entity mandibuloacral dysplasia type b.
no relations present in the abstract.
the retroperitoneal fibrosis is a type of inflammatory disorder; retroperitoneal fibrosis produces fibrosis behind the peritoneum; retroperitoneal fibrosis produces abnormal tissue growth often spreads to affect the ureters; retroperitoneal fibrosis produces ureters blocked by the excess tissue; retroperitoneal fibrosis produces tissue growth; the term "this disorder" refers back to the entity retroperitoneal fibrosis; retroperitoneal fibrosis produces methysergide; malignant tumors produces methysergide; the term "the disorder" refers back to the entity retroperitoneal fibrosis; the term "it" refers back to the entity retroperitoneal fibrosis.
the antiphospholipid syndrome is a type of autoimmune disorder; antiphospholipid syndrome produces thromboses; the acronym secondary antiphospholipid syndrome stands for antiphospholipid syndrome; the primary antiphospholipid syndrome is a type of aps; the systemic lupus erythematosus and the secondary antiphospholipid syndrome are synonyms; the secondary antiphospholipid syndrome is a type of aps; the presence of the aps increases the risk of developing the aps.
the term "the disorder" refers back to the entity floating-harbor syndrome.
melorheostosis produces sclerotic bone lesions.
the monilethrix is a type of inherited disorder; monilethrix produces sparse, dry, and/or brittle hair; monilethrix produces hair may lack luster; monilethrix produces alopecia; monilethrix produces papules; monilethrix produces perifollicular hyperkeratosis; monilethrix produces hair shaft resembles a string of evenly-spaced beads; the term "this disorder" refers back to the entity monilethrix.
the term "the disorder" refers back to the entity fibrous dysplasia; the term "the disorder" refers back to the entity fibrous dysplasia.
the meige syndrome is a type of neurological movement disorder; meige syndrome produces oromandibular dystonia; meige syndrome produces blepharospasm; the term "the disorder" refers back to the entity meige syndrome.
no relations present in the abstract.
the pseudocholinesterase deficiency is a type of genetic disorder; pseudocholinesterase deficiency produces very sensitive to any of several anesthetic agents; pseudocholinesterase deficiency produces very sensitive to derived from choline; pseudocholinesterase deficiency produces when anesthetic drugs administered muscles that work the lungs may become paralyzed; pseudocholinesterase deficiency produces shortage or absence of the enzyme pseudocholinesterase in their blood serum; pseudocholinesterase deficiency produces if anesthetic derivative of choline given apnea; pseudocholinesterase deficiency produces deficiency of the enzyme pseudocholinesterase; the term "it" refers back to the entity pseudocholinesterase deficiency; "it" produces apnea; infantile apnea produces apnea; infantile apnea produces pauses in breathing during an infant's sleep; central apnea produces no chest movements during the pauses in breathing; the diaphragmatic apnea and the central apnea are synonyms; "the disorder" produces chest movements but no passage of air through the mouth or nostrils; the term "the disorder" refers back to the entity obstructive apnea; the upper airway apnea and the obstructive apnea are synonyms; mixed apnea produces central apnea followed by or intermixed with an obstructive apnea.
ovotesticular disorder of sex development produces born with female ovaries and male testes; ovotesticular disorder of sex development produces gonads can be any combination of ovary, testes or combined ovary and testes (ovotestes); the acronym ovotesticular dsd stands for ovotesticular disorder of sex development; the ovotesticular dsd is a type of disorder of sex development.
ms produces muscle spasms; ms produces paralysis; balo disease produces muscle spasms; balo disease produces paralysis; balo disease produces intellectual impairment; balo disease produces physiological abnormalities; balo disease produces high fever; balo disease produces painful headaches; infectious disease produces high fever; infectious disease produces painful headaches; balo disease produces spasticity; balo disease produces weakness; balo disease produces pain; balo disease produces ataxia.
agat produces intellectual disabilities; agat produces delayed speech; agat produces seizure; ccds produces agat; ccds produces autism.
