data_dir = "/project/rvkavu2_uksr/sgu260/RareDis/PURE/Preprocess/entire_sentence/under_512/Xuguang_SODNER_data/new_data/"
task = "raredis"
output_dir = "/project/rvkavu2_uksr/sgu260/RareDis/PURE/outputs/Xuguang_SODNER/BioLinkBERT_large/10/entity/"
max_span_length = 10
train_batch_size =  8
eval_batch_size = 8
learning_rate = 1e-4
task_learning_rate = 1e-4
warmup_proportion = 0.1
num_epoch = 100
print_loss_step = 100
eval_per_epoch = 1
bertadam = False
do_train = True
train_shuffle = False
do_eval = True
eval_test = False
dev_pred_filename = "ent_pred_dev.json"
test_pred_filename = "ent_pred_test.json"
use_albert = False
# model = "dmis-lab/biobert-v1.1"
# model = "allenai/scibert_scivocab_uncased"
# model = "emilyalsentzer/Bio_ClinicalBERT"
# model = "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
# model = "/project/rvkavu2_uksr/sgu260/RareDis/PURE/outputs/Xuguang_SODNER/pubmedBERT_large/pre_trained_model/"
model = "michiyasunaga/BioLinkBERT-large"
bert_model_dir = None
seed = 0
context_window = 0
train_data = ""
dev_data = ""
test_data = ""

